//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biz.dfch.CS.Commons.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("biz.dfch.CS.Commons.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;links&quot;: [],
        ///	&quot;collection&quot;: [{
        ///		&quot;links&quot;: [{
        ///			&quot;title&quot;: &quot;KVM&quot;,
        ///			&quot;rel&quot;: &quot;machine&quot;,
        ///			&quot;type&quot;: &quot;application/vnd.abiquo.machine+json&quot;,
        ///			&quot;href&quot;: &quot;https://abiquo.example.com:443/api/admin/datacenters/1/racks/1/machines/2&quot;
        ///		},
        ///		{
        ///			&quot;title&quot;: &quot;Amsterdam DC&quot;,
        ///			&quot;rel&quot;: &quot;location&quot;,
        ///			&quot;type&quot;: &quot;application/vnd.abiquo.datacenter+json&quot;,
        ///			&quot;href&quot;: &quot;https://abiquo.example.com:443/api/cloud/locations/1&quot;
        ///		},
        ///		{
        ///			&quot;title&quot;: &quot;ABQ_f4d4ce1a-f109-4c7a-a358-e96dce4d5b80&quot;,
        ///			&quot;rel&quot;: &quot;edit&quot;,
        ///			&quot;type [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ACTION_VIRTUALMACHINES_RESPONSE {
            get {
                return ResourceManager.GetString("ACTION_VIRTUALMACHINES_RESPONSE", resourceCulture);
            }
        }
    }
}
